/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Tue May  2 21:07:19 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_textLCD_erpc_head_h_)
#define _textLCD_erpc_head_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief textLCDService identifiers */
enum _textLCDService_ids
{
    ktextLCDService_service_id = 1,
    ktextLCDService_Locate_id = 1,
    ktextLCDService_Cls_id = 2,
    ktextLCDService_Rows_id = 3,
    ktextLCDService_Columns_id = 4,
    ktextLCDService_Putc_id = 5,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name textLCDService
//@{
void Locate(uint8_t col, uint8_t row);

void Cls(void);

uint8_t Rows(void);

uint8_t Columns(void);

uint8_t Putc(uint8_t c);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _textLCD_erpc_head_h_
