/*
 * You can write copyrights rules here. These rules will be copied into the outputs.
 */

/*
 * Generated by erpcgen 1.10.0 on Mon May  1 01:12:06 2023.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_textLCD_erpc_head_server_h_)
#define _textLCD_erpc_head_server_h_

#ifdef __cplusplus
#include "erpc_server.hpp"
#include "erpc_codec.hpp"
extern "C"
{
#include "textLCD_erpc_head.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 11000 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for textLCDService.
 */
class textLCDService_service : public erpc::Service
{
public:
    textLCDService_service() : Service(ktextLCDService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for Locate of textLCDService interface. */
    erpc_status_t Locate_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Cls of textLCDService interface. */
    erpc_status_t Cls_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Rows of textLCDService interface. */
    erpc_status_t Rows_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Columns of textLCDService interface. */
    erpc_status_t Columns_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for Putc of textLCDService interface. */
    erpc_status_t Putc_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "textLCD_erpc_head.h"
#endif // __cplusplus

typedef void * erpc_service_t;

/*! @brief Return textLCDService_service service object. */
erpc_service_t create_textLCDService_service(void);

/*! @brief Destroy textLCDService_service service object. */
void destroy_textLCDService_service(erpc_service_t service);

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _textLCD_erpc_head_server_h_
